In [2]:
import scipy.sparse as sp
import networkx as nx
import numpy as np
from gurobi_optimods.mwis import maximum_weighted_independent_set

# Graph adjacency matrix (upper triangular) as a sparse matrix.
g = nx.cubical_graph()
adjacency_matrix = sp.triu(nx.to_scipy_sparse_array(g))
# Vertex weights
weights = np.array([2**i for i in range(8)])

# Compute maximum weighted independent set.
mwis = maximum_weighted_independent_set(adjacency_matrix, weights)

Restricted license - for non-production use only - expires 2025-11-24
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Ubuntu 20.04.6 LTS")

CPU model: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 12 rows, 8 columns and 24 nonzeros
Model fingerprint: 0x31a65d0e
Variable types: 0 continuous, 8 integer (8 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 165.0000000
Presolve removed 12 rows and 8 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 1: 165 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.650000000000e+02, best bound 

In [2]:
mwis

array([0, 2, 5, 7])

In [3]:
weights

array([  1,   2,   4,   8,  16,  32,  64, 128])

In [5]:
type(weights)

numpy.ndarray

In [6]:
adjacency_matrix

<8x8 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in COOrdinate format>

In [7]:
type(adjacency_matrix)

scipy.sparse._coo.coo_matrix

In [8]:
g

In [9]:
nx.to_scipy_sparse_array(g)

<8x8 sparse array of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [6]:
adjacency_matrix = np.array([[0.0]])
weights = np.array([0.3])
adjacency_mat = sp.triu(adjacency_matrix)


mwis = maximum_weighted_independent_set(adjacency_mat, weights)
mwis

Restricted license - for non-production use only - expires 2025-11-24
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Ubuntu 20.04.6 LTS")

CPU model: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 0 rows, 1 columns and 0 nonzeros
Model fingerprint: 0x0cb60b37
Variable types: 0 continuous, 1 integer (1 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [3e-01, 3e-01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 0.3000000

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 1: 0.3 
No other solutions better than 0.3

Optimal solution found (tolerance 1.00e-04)
Best objective 3.000000000000e-01, best bound 3.000000000000e-01, gap 0.0000%


array([0])

In [22]:
adjacency_mat = np.array([[0, 1, 0, 0],
                          [1, 0, 1, 0],
                          [0, 1, 0, 1],
                          [0, 0, 1, 0]])
# g = nx.cubical_graph(adjacency_mat)
adjacency_mat = sp.triu(adjacency_mat)
adjacency_mat

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in COOrdinate format>

In [23]:
weights = np.array([1, 2, 3, 4])
mwis = maximum_weighted_independent_set(adjacency_mat, weights)

Restricted license - for non-production use only - expires 2025-11-24
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Ubuntu 20.04.6 LTS")

CPU model: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 3 rows, 4 columns and 6 nonzeros
Model fingerprint: 0x5372b5eb
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 4e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 4.0000000
Presolve removed 3 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 2: 6 4 

Optimal solution found (tolerance 1.00e-04)
Best objective 6.000000000000e+00, best bound 6.000

In [24]:
mwis

array([1, 3])

In [7]:
def compute_adjacency_matrix(conflicting_tracks: tuple, n_tracks: int):
    adjacency_matrix = np.zeros((n_tracks, n_tracks))

    for track_a, track_b in conflicting_tracks:
        adjacency_matrix[track_a, track_b] = 1
        adjacency_matrix[track_b, track_a] = 1

    return adjacency_matrix

In [15]:
def compute_adjacency_matrix(conflicting_tracks: tuple, n_tracks: int):
    adjacency_matrix = np.ones((n_tracks, n_tracks))

    for track_a, track_b in conflicting_tracks:
        adjacency_matrix[track_a, track_b] = 0
        adjacency_matrix[track_b, track_a] = 0

    # all the diagonal elements are 0
    np.fill_diagonal(adjacency_matrix, 0)

    return adjacency_matrix

In [24]:
conflicting_tracks = []
node_weights = [-3.255213631532517e-06]

In [25]:
# conflicting_tracks = [(0, 1), (0, 3), (1, 0), (1, 2), (1, 3), (2, 1), (3, 0), (3, 1), (3, 4), (4, 3)]
# node_weights = [-6.510427263065034e-06, 13.08444718914689, -3.255213631532517e-06, 13.07295432407554, -3.255213631532517e-06]

In [26]:
node_weights = np.array(node_weights)
adjacency_matrix = compute_adjacency_matrix(conflicting_tracks, len(node_weights))
adjacency_matrix

array([[0.]])

In [27]:
node_weights

array([-3.25521363e-06])

In [28]:
adjacency_matrix = sp.triu(adjacency_matrix)
mwis_ids = maximum_weighted_independent_set( adjacency_matrix, node_weights)

Restricted license - for non-production use only - expires 2025-11-24
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Ubuntu 20.04.6 LTS")

CPU model: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 0 rows, 1 columns and 0 nonzeros
Model fingerprint: 0x58214885
Variable types: 0 continuous, 1 integer (1 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [3e-06, 3e-06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective -0.0000000

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 1: -0 
No other solutions better than -0

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%


In [29]:
set(mwis_ids)

set()